---
- name: Install ML + audio stack in virtualenv
  hosts: all
  become: yes

  vars:
    venv_path: /opt/mlaudioenv

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install system dependencies
      apt:
        name:
          - python3
          - python3-venv
          - python3-dev
          - python3-pip
          - build-essential
          - cmake
          - gfortran
          - libblas-dev
          - liblapack-dev
          - libatlas-base-dev
          - libsndfile1-dev
          - libasound2t64
          - libasound2-dev
          - portaudio19-dev
          - libportaudio2
          - libportaudiocpp0
          - ffmpeg
          - libsdl2-dev
          - libsdl2-image-dev
          - libsdl2-mixer-dev
          - libsdl2-ttf-dev
          - libogg-dev
          - libvorbis-dev
          - libflac-dev
          - libjpeg-dev
          - libpng-dev
          - libfreetype6-dev
          - libhdf5-dev
          - hdf5-tools
        state: present

    - name: Create virtual environment
      command: python3 -m venv {{ venv_path }}
      args:
        creates: "{{ venv_path }}/bin/activate"

    - name: Upgrade pip inside venv
      command: "{{ venv_path }}/bin/pip install -U pip setuptools wheel"

    - name: Install Python packages inside venv
      command: "{{ venv_path }}/bin/pip install numpy librosa soundfile matplotlib seaborn scikit-learn tensorflow tqdm sounddevice scipy gTTS pygame"
