---
- name: Full Python ML + Audio environment
  hosts: all
  become: yes

  vars:
    python_packages:
      - numpy
      - librosa
      - soundfile
      - matplotlib
      - seaborn
      - scikit-learn
      - tensorflow
      - tqdm
      - sounddevice
      - scipy
      - gTTS
      - pygame

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install system dependencies for audio, ML, and build tools
      apt:
        name:
          - python3
          - python3-dev
          - python3-pip
          - python3-venv
          - build-essential
          - cmake
          - git

          # Numerical libraries (BLAS/LAPACK)
          - libblas-dev
          - liblapack-dev
          - libatlas-base-dev
          - gfortran

          # Sound + audio dependencies
          - libasound2t64
          - libasound2-dev
          - libsndfile1
          - libsndfile1-dev
          - portaudio19-dev
          - libportaudio2
          - libportaudiocpp0
          - alsa-utils

          # FFmpeg for audio/video decoding
          - ffmpeg

          # SDL for pygame
          - libsdl2-dev
          - libsdl2-image-dev
          - libsdl2-mixer-dev
          - libsdl2-ttf-dev

          # Codec libs
          - libogg-dev
          - libvorbis-dev
          - libflac-dev

          # Misc for scipy/matplotlib
          - zlib1g-dev
          - libjpeg-dev
          - libpng-dev
          - libfreetype6-dev
          - pkg-config

          # TensorFlow recommended libraries
          - libhdf5-dev
          - hdf5-tools
        state: present

    - name: Upgrade pip
      pip:
        name: pip
        executable: pip3
        state: latest

    - name: Install required Python packages
      pip:
        name: "{{ python_packages }}"
        executable: pip3
        state: present
