---
- name: Register Checkmk agents with TLS
  hosts: SuperComputer
  become: true
  tasks:
    - name: Register Checkmk agent with TLS
      ansible.builtin.shell: |
        cmk-agent-ctl register \
          --hostname "$(hostname -f)" \
          --server 10.64.0.156 \
          --site monitoring \
          --user agent_registration \
          --password 'zm(nhkbWf6jYg7wf' \
          --trust-cert

