---
- name: Install Lambda Stack on servers
  hosts: lambda
  become: true
  vars_files:
    - vault.yml

  tasks:
    - name: Fix broken/half-installed packages
      ansible.builtin.shell: dpkg --configure -a

    - name: Update system packages
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install Lambda Stack (non-interactive)
      ansible.builtin.shell: |
        wget -nv -O- https://lambda.ai/install-lambda-stack.sh | I_AGREE_TO_THE_CUDNN_LICENSE=1 sh -

