---
- name: Add new user to Linux servers
  hosts: all
  become: true

  vars:
    group: students

  tasks:
    - name: Ensure 'students' group exists
      ansible.builtin.group:
        name: "{{ group }}"
        state: present

    - name: Ensure user exists and set password
      ansible.builtin.user:
        name: "{{ username }}"
        comment: "{{ full_name }}"
        shell: /bin/bash
        create_home: yes
        password: "{{ password | password_hash('sha512') }}"
        groups: "{{ group }}"
        append: yes

    - name: Force password change on first login
      ansible.builtin.command:
        cmd: chage -d 0 {{ username }}
      become: true

    - name: Debug confirmation message
      ansible.builtin.debug:
        msg: "User {{ username }} created and must change password at first login."
