---
- name: Add new user to Linux servers
  hosts: all
  become: true
  vars:
    username: "{{ username }}"
    full_name: "{{ full_name }}"
    email: "{{ email }}"
    password: "{{ password }}"

  tasks:
    - name: Ensure user exists
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /bin/bash
        create_home: yes
        password: "{{ password | password_hash('sha512') }}"

    - name: Set full name and email as comment
      ansible.builtin.command:
        cmd: "chfn -f '{{ full_name }} ({{ email }})' {{ username }}"
