---
- name: Install NVIDIA Driver, CUDA 13.0, and TensorFlow GPU on Ubuntu 24.04
  hosts: all
  become: yes
  vars:
    cuda_version: "13-0"
    venv_dir: "/opt/tf_gpu_env"

  tasks:
    - name: Ensure apt cache is up to date
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install base dependencies
      apt:
        name:
          - build-essential
          - dkms
          - linux-headers-{{ ansible_kernel }}
          - python3-venv
          - python3-pip
          - wget
          - gnupg
        state: present

    - name: Clean up any existing NVIDIA or CUDA packages
      shell: |
        apt-get clean
        apt-get autoremove -y || true
        apt-get purge -y 'cuda*' 'nvidia-*' || true
        apt-get update -y
      args:
        executable: /bin/bash

    - name: Add NVIDIA CUDA repository keyring
      get_url:
        url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
        dest: /tmp/cuda-keyring.deb
        mode: '0644'

    - name: Install CUDA repository keyring
      apt:
        deb: /tmp/cuda-keyring.deb

    - name: Update apt cache after adding repo
      apt:
        update_cache: yes

    - name: Install the latest recommended NVIDIA driver (proprietary flavor)
      apt:
        name: nvidia-driver-550
        state: present

    # Optional: open-source driver alternative
    # - name: Install NVIDIA open kernel driver
    #   apt:
    #     name: nvidia-open
    #     state: present

    - name: Install CUDA toolkit only (without bundled driver)
      apt:
        name: "cuda-toolkit-{{ cuda_version }}"
        state: present

    - name: Add CUDA to PATH
      lineinfile:
        path: /etc/profile.d/cuda.sh
        line: 'export PATH=/usr/local/cuda/bin:$PATH'
        create: yes
        mode: '0644'

    - name: Autoremove any unnecessary packages
      apt:
        autoremove: yes

    - name: Clean APT cache
      shell: apt-get clean
      args:
        executable: /bin/bash

    - name: Reboot after driver and CUDA install
      reboot:
        msg: "Rebooting to load new NVIDIA kernel modules..."
        pre_reboot_delay: 5
        reboot_timeout: 600
        test_command: nvidia-smi

    - name: Verify NVIDIA driver installation
      shell: nvidia-smi
      register: nvidia_smi
      changed_when: false
      failed_when: nvidia_smi.rc != 0

    - debug:
        msg: "{{ nvidia_smi.stdout }}"

    - name: Create Python virtual environment for TensorFlow
      command: python3 -m venv {{ venv_dir }}
      args:
        creates: "{{ venv_dir }}/bin/activate"

    - name: Upgrade pip inside venv
      pip:
        name: pip
        state: latest
        virtualenv: "{{ venv_dir }}"
        virtualenv_command: python3 -m venv

    - name: Install TensorFlow with GPU support
      pip:
        name: "tensorflow[and-cuda]"
        state: latest
        virtualenv: "{{ venv_dir }}"
        virtualenv_command: python3 -m venv

    - name: Verify TensorFlow GPU detection
      shell: |
        source {{ venv_dir }}/bin/activate
        python -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
      args:
        executable: /bin/bash
      register: tf_gpu
      changed_when: false

    - debug:
        msg: "{{ tf_gpu.stdout }}"
