---
- name: Install NVIDIA Driver, CUDA 13.0, and TensorFlow GPU
  hosts: all
  become: yes
  vars:
    cuda_version: "13-0"
    venv_dir: "/opt/tf_gpu_env"

  tasks:
    - name: Ensure apt cache is up to date
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install base dependencies
      apt:
        name:
          - build-essential
          - dkms
          - linux-headers-{{ ansible_kernel }}
          - python3-venv
          - python3-pip
          - wget
          - gnupg
          - lsb-release
        state: present

    - name: Download NVIDIA CUDA keyring
      ansible.builtin.get_url:
        url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
        dest: /tmp/cuda-keyring.deb
        mode: '0644'

    - name: Install CUDA keyring
      ansible.builtin.apt:
        deb: /tmp/cuda-keyring.deb

    - name: Update apt cache after adding CUDA repo
      apt:
        update_cache: yes

    - name: Install NVIDIA proprietary driver
      apt:
        name: cuda-drivers
        state: present

    - name: Install CUDA toolkit
      apt:
        name: "cuda-toolkit-{{ cuda_version }}"
        state: present

    - name: Create CUDA environment setup script
      copy:
        dest: /etc/profile.d/cuda.sh
        content: |
          export PATH=/usr/local/cuda/bin:$PATH
          export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
        mode: '0644'

    - name: Check if reboot is required (after driver install)
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot system if required
      reboot:
        msg: "Rebooting after NVIDIA driver installation..."
      when: reboot_required_file.stat.exists

    - name: Create Python virtual environment for TensorFlow
      command: python3 -m venv {{ venv_dir }}
      args:
        creates: "{{ venv_dir }}/bin/activate"

    - name: Upgrade pip in virtual environment
      pip:
        name: pip
        state: latest
        virtualenv: "{{ venv_dir }}"
        virtualenv_command: python3 -m venv

    - name: Install TensorFlow with GPU support
      pip:
        name: "tensorflow[and-cuda]"
        state: latest
        virtualenv: "{{ venv_dir }}"
        virtualenv_command: python3 -m venv
      register: tf_install
      ignore_errors: yes

    - name: Fallback - install latest stable TensorFlow if CUDA 13 not supported
      pip:
        name: "tensorflow==2.18.*"
        state: present
        virtualenv: "{{ venv_dir }}"
        virtualenv_command: python3 -m venv
      when: tf_install is failed

    - name: Verify NVIDIA driver (nvidia-smi)
      shell: nvidia-smi
      register: nvidia_smi
      changed_when: false
      ignore_errors: yes

    - debug:
        msg: "{{ nvidia_smi.stdout | default('NVIDIA driver not detected') }}"

    - name: Verify TensorFlow GPU detection
      shell: |
        source {{ venv_dir }}/bin/activate
        python -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
      register: tf_gpu
      changed_when: false
      ignore_errors: yes

    - debug:
        msg: "{{ tf_gpu.stdout | default('TensorFlow GPU not detected') }}"
